# Generated by Django 4.2.1 on 2023-09-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0002_remove_hotel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_Main_Img1', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'Hotel1',
            },
        ),
        migrations.CreateModel(
            name='Hotel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_Main_Img2', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'Hotel2',
            },
        ),
        migrations.CreateModel(
            name='Hotel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_Main_Img3', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'Hotel3',
            },
        ),
        migrations.CreateModel(
            name='Hotel4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_Main_Img4', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'Hotel4',
            },
        ),
    ]
