# Generated by Django 4.2.1 on 2023-11-26 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='com_mst',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('c1', models.IntegerField()),
                ('c2', models.IntegerField()),
                ('c3', models.IntegerField()),
                ('c4', models.IntegerField()),
                ('total', models.IntegerField(default=0)),
                ('c5', models.IntegerField()),
                ('total1', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'component_table',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('sem_id', models.AutoField(primary_key=True, serialize=False)),
                ('sem_name', models.CharField(max_length=10)),
                ('cid', models.ForeignKey(db_column='cid', default='', on_delete=django.db.models.deletion.CASCADE, to='StuApp.course')),
            ],
            options={
                'db_table': 'Semester',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('enrollment', models.CharField(default='', max_length=100)),
                ('cid', models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to='StuApp.course')),
                ('sem_id', models.ForeignKey(db_column='sem_id', default=True, on_delete=django.db.models.deletion.CASCADE, to='StuApp.semester')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='subject_type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'subject_type',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(default='', max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.ForeignKey(db_column='cid', default='', on_delete=django.db.models.deletion.CASCADE, to='StuApp.course')),
                ('com_id', models.ForeignKey(db_column='com_id', default='', on_delete=django.db.models.deletion.CASCADE, to='StuApp.com_mst')),
                ('sid', models.ForeignKey(db_column='sid', default='', on_delete=django.db.models.deletion.CASCADE, to='StuApp.student')),
            ],
            options={
                'db_table': 'subject_table',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Provisional_result',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_sem', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('sid', models.ForeignKey(db_column='sid', default='', on_delete=django.db.models.deletion.CASCADE, to='StuApp.student')),
            ],
            options={
                'db_table': 'Provisional_result',
            },
        ),
        migrations.CreateModel(
            name='Final_result',
            fields=[
                ('final_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=100)),
                ('sid', models.ForeignKey(db_column='sid', default='', on_delete=django.db.models.deletion.CASCADE, to='StuApp.student')),
            ],
            options={
                'db_table': 'Final_result',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='did',
            field=models.ForeignKey(db_column='did', on_delete=django.db.models.deletion.CASCADE, to='StuApp.department'),
        ),
        migrations.AddField(
            model_name='com_mst',
            name='cid',
            field=models.ForeignKey(db_column='cid', default='', on_delete=django.db.models.deletion.CASCADE, to='StuApp.course'),
        ),
        migrations.AddField(
            model_name='com_mst',
            name='sid',
            field=models.ForeignKey(db_column='sid', default='', on_delete=django.db.models.deletion.CASCADE, to='StuApp.student'),
        ),
        migrations.AddField(
            model_name='com_mst',
            name='type_id',
            field=models.ForeignKey(db_column='type_id', default='', on_delete=django.db.models.deletion.CASCADE, to='StuApp.subject_type'),
        ),
        migrations.CreateModel(
            name='Bonafide_Certificate',
            fields=[
                ('bono_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('sid', models.ForeignKey(db_column='sid', default='', on_delete=django.db.models.deletion.CASCADE, to='StuApp.student')),
            ],
            options={
                'db_table': 'Bonafide_Certificate',
            },
        ),
    ]
