# Generated by Django 4.2.1 on 2023-12-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StuApp', '0004_alter_final_result_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='com_mst',
            name='c6',
            field=models.IntegerField(default=0),
        ),
    ]
