# Generated by Django 4.2.1 on 2023-12-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StuApp', '0005_com_mst_c6'),
    ]

    operations = [
        migrations.AddField(
            model_name='com_mst1',
            name='c6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='com_mst2',
            name='c6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='com_mst3',
            name='c6',
            field=models.IntegerField(default=0),
        ),
    ]
