# Generated by Django 4.2.1 on 2023-12-09 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StuApp', '0006_com_mst1_c6_com_mst2_c6_com_mst3_c6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cid',
            field=models.ForeignKey(db_column='cid', default='', on_delete=django.db.models.deletion.CASCADE, to='StuApp.course'),
        ),
    ]
