# Generated by Django 4.2.1 on 2023-12-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StuApp', '0008_remove_student_cid_remove_student_sem_id_student_did'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_Main_Img', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'slider1',
            },
        ),
    ]
