# Generated by Django 4.2.1 on 2023-12-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StuApp', '0009_slider1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slider1',
            table='slider11',
        ),
    ]
